package com.ilustris.sagai.core.ai.prompts

/**
 * Shared local instructions for any `artwork` field (Chapter, Saga) generated by the AI.
 *
 * These are merged directly into prompts via [com.ilustris.sagai.core.ai.model.mergeInstructions]
 * instead of living in a remote blueprint, since `artwork` field names alone (reflection-based
 * output schema) carry no intent to the model on their own.
 */
object ArtworkPrompts {
    val ARTWORK_DIRECTION_INSTRUCTIONS: Map<String, Any> =
        mapOf(
            "ARTWORK DIRECTION" to
                mapOf(
                    "Purpose" to
                        "The `artwork` field is a written key-art concept, not a summary. It is handed " +
                            "directly to an image generator, so every word must earn its place on the canvas.",
                    "Anchor the protagonist" to
                        "Center the scene on the protagonist (or point-of-view character). State exactly what " +
                            "they are doing, feeling, and confronting in this one moment — never a generic pose " +
                            "or an anonymous silhouette.",
                    "Ground it in this story" to
                        "Pull in at least one concrete, specific detail unique to this narrative (an object, a " +
                            "location, a scar, a relationship, a consequence of the plot). If the sentence could " +
                            "describe a different story with the names swapped, it has failed.",
                    "Reject AI slop" to
                        "Never default to 'epic hero staring into the distance', glowing generic magic, stock " +
                            "power poses, or vague adjectives like 'mysterious' and 'powerful' with nothing " +
                            "behind them. Every visual choice must be earned by what actually happened or is at " +
                            "stake right now.",
                    "Be visually actionable" to
                        "Write one vivid paragraph in concrete visual terms: composition, expression, lighting, " +
                            "key colors, and the single emotional beat being captured. Not a list, not a mood " +
                            "board — one decisive image.",
                ),
        )
}
