package com.ilustris.sagai.features.saga.chat.data.model

/**
 * Represents who authored a message in the database.
 *
 * DESIGN NOTE: We intentionally keep this minimal. The tag system (<narrator>, <action>, <think>)
 * handles all narrative layering *within* a message's text. SenderType is purely about
 * distinguishing player input from AI output at the data layer.
 *
 * - USER    → written by the player, always sent locally, never generated by the AI
 * - CHARACTER → generated by the AI; its text may contain any combination of inline tags
 *
 * The legacy NARRATOR/ACTION/THOUGHT variants are retained as fallbacks so that any old
 * database rows with those string values are read safely and mapped to CHARACTER,
 * rather than crashing with an IllegalArgumentException.
 */
enum class SenderType {
    USER,
    CHARACTER,

    @Deprecated("Use CHARACTER + inline <think> tag instead")
    THOUGHT,

    @Deprecated("Use CHARACTER + inline <action> tag instead")
    ACTION,

    @Deprecated("Use CHARACTER + inline <narrator> tag instead")
    NARRATOR,
    ;

    /**
     * Normalizes legacy sender types to their modern equivalent.
     * Call this whenever reading a SenderType from the database.
     */
    fun normalize(): SenderType =
        when (this) {
            NARRATOR, THOUGHT, ACTION -> CHARACTER
            else -> this
        }

    companion object {
        /**
         * Safe parsing — returns CHARACTER as the fallback instead of throwing.
         * This is what protects us from old/corrupted enum string values in the DB.
         */
        fun fromString(value: String?): SenderType =
            entries
                .firstOrNull { it.name.equals(value, ignoreCase = true) }
                ?.normalize()
                ?: CHARACTER
    }
}

fun SenderType.isCharacter() = this == SenderType.CHARACTER
