package com.ilustris.sagai.features.timeline.data.model

import com.ilustris.sagai.features.wiki.data.model.WikiType

/**
 * Represents a complete lore update generated by AI in a single shot.
 * This includes the event title/summary, character milestones, relationship shifts, and world-building (wikis).
 */
data class UnifiedLoreUpdate(
    val title: String = "",
    val content: String = "",
    val emotionalReview: String? = null,
    val characterEvents: List<GeneratedCharacterEvent> = emptyList(),
    val relationshipUpdates: List<GeneratedRelationshipUpdate> = emptyList(),
    val wikiUpdates: List<GeneratedWikiUpdate> = emptyList(),
)

data class GeneratedCharacterEvent(
    val characterName: String = "",
    val title: String = "",
    val summary: String = "",
)

data class GeneratedRelationshipUpdate(
    val characterOne: String = "",
    val characterTwo: String = "",
    val title: String = "",
    val description: String = "",
    val emoji: String = "",
)

data class GeneratedWikiUpdate(
    val title: String = "",
    val content: String = "",
    val type: WikiType = WikiType.OTHER,
    val emojiTag: String? = null,
)
